### ISSUE TITLE
allow onClick for buttons

### ISSUE THREAD

**Issue by reluem** [contao-bootstrap/buttons#3]
at the moment one can enter several html tags such as "class": "btn-lg".
For google analytics tracking, it would be nice if you could also add onClick events.
Unfortunately, the entered strings seem to be converted to unicode, and a simple `(` becomes `&#40;`, thus breaking the Google tracking.

onClick should look like this: `onClick="gaTrackEvent('E-Mail sent', 'foo@bar.com');"`

Is there any way to change this?

**Comment by dmolineus** [comment]
I recommend to use a custom template for it. Do you need it for the button or buttons element?

**Comment by reluem** [comment]
hi @dmolineus, sorry for not answering! 
I would need it for the button element, but rather a generic solution than 'hacking' individual templates.
